datasources:
  default:
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver
    username: sa
    password: 12345

#gera a tabela automaticamente banco de dados
jpa.default.properties.hibernate.hbm2ddl.auto: update
##
# Habilita log de contexto transacional
##
logger:
  levels:
    io.micronaut.transaction: DEBUG